// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yojklwblzbtrsnlqtrhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlvamtsd2JsemJ0cnNubHF0cmhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNjg4NjUsImV4cCI6MjA1Njk0NDg2NX0.h3XP8s6HwlSY0UMxdyt8gwSrEo86xD9_t4wgoOaFZyo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);